services:
  - type: web
    name: stt-frontend
    env: docker
    rootDir: frontend
    plan: free
    envVars:
      - key: STT_API_URL
        value: https://stt-backend.onrender.com

  - type: web
    name: stt-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: WHISPER_API_URL
        value: http://whisper:8000

  - type: web
    name: stt-whisper
    env: docker
    rootDir: whisper
    plan: free
    autoDeploy: true
